#!/usr/bin/env ruby
require "io/console"
require "curses"

COLORS = [
  16,  # 0,0,0
  52,  # 1,0,0
  88,  # 2,0,0
  124, # 3,0,0
  160, # 4,0,0
  196, # 5,0,0
  202, # 5,1,0
  208, # 5,2,0
  214, # 5,3,0
  220, # 5,4,0
  226, # 5,5,0
  231, # 5,5,5
]
STRING = " "

# 下段にランダムに数字を入れます
# 上の段に下3個の平均を入れます
# さら上の段に下4個の平均を入れます
# 数字によって色づけをします
# 下段の数字を変えます
# 細かくします
# もっと細かくします
# ノイズを足します

def generate_array
  Kernel.srand ARGV[0].to_i if ARGV[0]

  window_height, window_width = IO.console.winsize # [height, width]
  terminal = Array.new(window_height) { Array.new(window_width) }

  # 下段にランダムに数字を入れます
  last_row = terminal[-1]
  last_row.fill { rand(100) }

  terminal
end

def update_last_row(terminal)
  # 下段の数字を変えます
  last_row = terminal[-1]
  last_row.fill { |i|
    (last_row[i] + rand(-2..2)).clamp(0, 99)
  }
  terminal
end

def update_array(terminal)
  window_height = terminal.length
  window_width  = terminal[0].length

  # 上の段に下3個の平均を入れます
  last_row = terminal[-1]
  next_row = terminal[-2]
  next_row.fill { |i|
    case i
    when 0
      (last_row[i] + last_row[i+1]) / 2
    when window_width - 1
      (last_row[i-1] + last_row[i]) / 2
    else
      (last_row[i-1] + last_row[i] + last_row[i+1]) / 3
    end
  }

  # さら上の段に下4個の平均を入れます
  (window_height - 2).times do |i|
    row = terminal[window_height - (3 + i)]
    row_1 = terminal[window_height - (2 + i)]
    row_2 = terminal[window_height - (1 + i)]
    row.fill { |j|
      case j
      when 0
        (row_1[j] + row_1[j+1] + row_2[j]) / 3
      when window_width - 1
        (row_1[j-1] + row_1[j] + row_2[j]) / 3
      else
        (row_1[j-1] + row_1[j] + row_1[j+1] + row_2[j]) / 4
      end
    }
  end
  terminal
end

def colorize(terminal)
  # 数字によって色づけをします
  terminal.map { |row|
    row.map { |cell|
      COLORS[(cell / (100.0 / COLORS.length)).to_i]
    }
  }
end

def main
  Curses.init_screen
  Curses.start_color

  COLORS.each { |color| Curses.init_pair(color, color, color) }

  terminal = generate_array
  loop {
    terminal = update_last_row(terminal)
    terminal = update_array(terminal)
    colorized_terminal = colorize(terminal)
    colorized_terminal.each { |row|
      row.each { |cell|
        Curses.attron(Curses.color_pair(cell)) {
          Curses.addstr(STRING)
        }
      }
    }
    Curses.refresh
    sleep 0.5
    Curses.clear
  }
ensure
  Curses.close_screen
end

main
