#!/usr/bin/env ruby
require "io/console"

# 下段にランダムに数字を入れます
# 上の段に下3個の平均を入れます
# さら上の段に下4個の平均を入れます
# 数字によって色づけをします
# 下段の数字を変えます
# 細かくします
# もっと細かくします
# ノイズを足します
def main
  window_height, window_width = IO.console.winsize # [height, width]
  terminal = Array.new(window_height) { Array.new(window_width) }

  # 下段にランダムに数字を入れます
  last_row = terminal[-1]
  last_row.fill { rand(100) }
  p terminal[-1]
end

main
